zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"
kafka1:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9992:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "192.168.42.45"
    KAFKA_CREATE_TOPICS: "test-messages:5:3"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
kafka2:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9993:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "192.168.42.45"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
kafka3:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9994:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "192.168.42.45"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
